#!/bin/sh
## Adaptation Grassland in Lucheng 2018.12.08

echo -e "*****************************************************"
echo -e "\e[1;31m     SSR 安装脚本 \e[0m"
echo -e "*****************************************************\n"

echo -e "\e[1;33m >	1. 安装 \e[1;33mpadavan \033[41;37m 内置 Adbyby \e[0m\n"

echo -e "\e[1;31m >	2. 卸载 \e[1;33mpadavan Adbyby \e[0m\n"

echo -e "\e[1;33m >	3. 更新 \e[1;33mpadavan \033[44;37m Adbyby 规则 \e[0m\n"

echo -e "\e[1;31m >	0. \033[41;37m退出\e[0m\n"

echo -e -n "\e[44;37m 请输入数字继续执行: \e[0m" 
read Function_options
if [ "$Function_options" == "1" ]; then
	if [ ! -d "/etc/storage/shadowsocksr" ]; then
		if [ -f "/tmp/SSR.tar.bz2" ]; then
			tar -xjvf /tmp/SSR.tar.bz2 -C /etc
			#wget --no-check-certificate https://raw.githubusercontent.com/896660689/SSR-000/master/ssr_install -O /tmp/ssr_install && chmod +x /tmp/ssr_install && . /tmp/ssr_install && sleep 3
			echo -e "\e[1;34m ssr 安装完成;开始运行 \e[0m\n" && sleep 3
		else
			echo -e "\e[1;34m 下载 Adbyby 脚本文件开始安装 \e[0m\n"
			#wget --no-check-certificate https://github.com/896660689/LS-SSR/blob/master/SSR_Mproxy_Pdnsd-1812D.tar.bz2 -O /tmp/SSR.tar.bz2
			#wget --no-check-certificate -t 15 -T 50 https://raw.githubusercontent.com/896660689/LS-SSR/master/SSR_Mproxy_Pdnsd-1812D.tar.bz2 -O /tmp/SSR.tar.bz2 && sleep 2
			wget --no-check-certificate -t 15 -T 50 https://raw.githubusercontent.com/896660689/LS-SSR/master/SSR_Pdnsd-1812AShuangHao.tar.bz2 -O /tmp/SSR.tar.bz2 && sleep 2
			tar -xjvf /tmp/SSR.tar.bz2 -C /etc && sleep 1
		fi
		sh /etc/storage/shadowsocksr/ssr_install
		[ -f /tmp/SSR.tar.bz2 ] && rm -f /tmp/SSR.tar.bz2; sh /tmp/ssr_an
	else
		sh /etc/storage/shadowsocksr/ssr_install
		echo -e "\e[1;34m 安装完成;开始运行 \e[0m\n" && sleep 3
		[ -f /tmp/SSR.tar.bz2 ] && rm -f /tmp/SSR.tar.bz2; sh /tmp/ssr_an
	fi
fi

if [ "$Function_options" == "2" ]; then
	if [ ! -f "/etc/storage/shadowsocksr/ssr-stop" ]; then
		echo -e "\e[1;34m 没有发现 SSR,返回主菜单 \e[0m\n" && sleep 3
	else
		sh /etc/storage/shadowsocksr/ssr-stop
		echo -e "\e[1;34m 卸载已完成,返回主菜单 \e[0m\n" && sleep 3
	fi
	sh /tmp/ssr_an
fi

if [ "$Function_options" == "3" ]; then
	if [ ! -d "/etc/storage/dnsmasq.d/gfw" ]; then
		wget --no-check-certificate https://raw.githubusercontent.com/896660689/Hsfq/master/Hsfq_install -O /tmp/Hsfq_install;sh /tmp/Hsfq_install
	else
		echo -e "\e[1;34m 发现SSR文件夹,请选择纯净去AD版安装 \e[0m\n" && sleep 3
		wget --no-check-certificate https://raw.githubusercontent.com/896660689/Hsfq/master/Hsfq_install -O /tmp/Hsfq_install;sh /tmp/Hsfq_install
	fi
	sh /tmp/ssr_an
	#[ -f /tmp/ssr_an ] && rm -f /tmp/ssr_an
fi

if [ "$Function_options" == "0" ]; then
	echo -e "*****************************************************"
	echo -e "*                   Time:`date +'%Y-%m-%d'`                    *"
	echo -e "*****************************************************\n"
	[ -f /tmp/ssr_an ] && rm -f /tmp/ssr_an
fi
